const remove = (...blocks) => blocks.map((block) => [block, "air"]);
const swap = (from, to) => [[from, to]];

const FLOWERS = [
  "dandelion", "poppy", "blue_orchid", "allium", "azure_bluet", "red_tulip",
  "orange_tulip", "white_tulip", "pink_tulip", "oxeye_daisy", "cornflower",
  "lily_of_the_valley", "sunflower", "lilac", "rose_bush", "peony",
  "torchflower", "pitcher_plant", "wither_rose"
];
const FLORA = [...FLOWERS, "short_grass", "tall_grass", "fern", "large_fern", "deadbush", "seagrass", "tall_seagrass", "vine", "glow_lichen", "moss_carpet", "pink_petals", "wildflowers", "leaf_litter", "bush", "firefly_bush", "cactus_flower", "spore_blossom", "hanging_roots", "crimson_roots", "warped_roots", "nether_sprouts", "brown_mushroom", "red_mushroom"];
const LIGHTS = ["torch", "soul_torch", "redstone_torch", "lantern", "soul_lantern", "glowstone", "sea_lantern", "shroomlight", "ochre_froglight", "verdant_froglight", "pearlescent_froglight", "jack_o_lantern", "campfire", "soul_campfire", "end_rod", "beacon", "light_block", "lava", "fire", "soul_fire", "magma", "redstone_lamp", "respawn_anchor", "conduit", "end_portal", "portal", "candle", "white_candle", "orange_candle", "magenta_candle", "light_blue_candle", "yellow_candle", "lime_candle", "pink_candle", "gray_candle", "light_gray_candle", "cyan_candle", "purple_candle", "blue_candle", "brown_candle", "green_candle", "red_candle", "black_candle"];

const SLABS = [
  ["oak", "oak_planks"], ["spruce", "spruce_planks"], ["birch", "birch_planks"],
  ["jungle", "jungle_planks"], ["acacia", "acacia_planks"], ["dark_oak", "dark_oak_planks"],
  ["mangrove", "mangrove_planks"], ["cherry", "cherry_planks"], ["bamboo", "bamboo_planks"],
  ["crimson", "crimson_planks"], ["warped", "warped_planks"], ["cobblestone", "cobblestone"],
  ["brick", "bricks"], ["stone_brick", "stone_bricks"], ["mud_brick", "mud_bricks"],
  ["nether_brick", "nether_bricks"], ["quartz", "quartz_block"], ["purpur", "purpur_block"],
  ["blackstone", "blackstone"], ["cobbled_deepslate", "cobbled_deepslate"],
  ["polished_deepslate", "polished_deepslate"], ["deepslate_brick", "deepslate_bricks"],
  ["deepslate_tile", "deepslate_tiles"]
].map(([kind, block]) => [`${kind}_slab`, block]);

const STAIRS = [
  ["oak", "oak_planks"], ["spruce", "spruce_planks"], ["birch", "birch_planks"],
  ["jungle", "jungle_planks"], ["acacia", "acacia_planks"], ["dark_oak", "dark_oak_planks"],
  ["mangrove", "mangrove_planks"], ["cherry", "cherry_planks"], ["bamboo", "bamboo_planks"],
  ["crimson", "crimson_planks"], ["warped", "warped_planks"], ["stone", "stone"],
  ["cobblestone", "cobblestone"], ["brick", "bricks"], ["stone_brick", "stone_bricks"],
  ["sandstone", "sandstone"], ["red_sandstone", "red_sandstone"],
  ["nether_brick", "nether_bricks"], ["quartz", "quartz_block"], ["purpur", "purpur_block"],
  ["prismarine", "prismarine"], ["dark_prismarine", "dark_prismarine"],
  ["blackstone", "blackstone"], ["cobbled_deepslate", "cobbled_deepslate"],
  ["polished_deepslate", "polished_deepslate"], ["deepslate_brick", "deepslate_bricks"],
  ["deepslate_tile", "deepslate_tiles"], ["mud_brick", "mud_bricks"]
].map(([kind, block]) => [`${kind}_stairs`, block]);

const GLASS_PANES = ["glass", "white_stained_glass", "orange_stained_glass", "magenta_stained_glass", "light_blue_stained_glass", "yellow_stained_glass", "lime_stained_glass", "pink_stained_glass", "gray_stained_glass", "light_gray_stained_glass", "cyan_stained_glass", "purple_stained_glass", "blue_stained_glass", "brown_stained_glass", "green_stained_glass", "red_stained_glass", "black_stained_glass"].map((glass) => [glass === "glass" ? "glass_pane" : `${glass}_pane`, glass]);

export const REALITY_RECIPES = new Map([
  [0, { name: "Original" }],
  [1, { name: "Perfect copy" }],
  [2, { name: "Gravel sand", replacements: swap("sand", "gravel") }],
  [3, { name: "No flowers", replacements: remove(...FLOWERS) }],
  [4, { name: "Thick windows", replacements: GLASS_PANES }],
  [5, { name: "No slabs", replacements: SLABS }],
  [6, { name: "No stairs", replacements: STAIRS }],
  [7, { name: "Silent world", noMobs: true }],
  [8, { name: "Missing pieces", scan: { type: "random_air", count: 250 } }],
  [9, { name: "Spruce impostors", replacements: swap("oak_log", "spruce_log") }],
  [10, { name: "No flora", replacements: remove(...FLORA) }],
  [11, { name: "Cobble stone", replacements: swap("stone", "cobblestone") }],
  [12, { name: "Red torches", replacements: swap("torch", "redstone_torch") }],
  [13, { name: "Lightless", replacements: remove(...LIGHTS) }],
  [14, { name: "Bedrock fog", fog: "coherence:bedrock_fog" }],
  [15, { name: "Missing chunk", voidChunk: { minX: 0, maxX: 15, minZ: 0, maxZ: 15 } }],
  [16, { name: "Dead lawn", replacements: swap("grass_block", "dirt") }],
  [17, { name: "Cobble everything", scan: { type: "solidify", block: "cobblestone" } }],
  [18, { name: "Lava water", replacements: swap("water", "lava") }],
  [19, { name: "Crimson fog", fog: "coherence:crimson_fog" }],
  [20, { name: "Sickly fog", fog: "coherence:sickly_fog" }],
  [21, { name: "Violet fog", fog: "coherence:violet_fog" }],
  [22, { name: "Golden fog", fog: "coherence:golden_fog" }],
  [23, { name: "Inverted view", invertedView: true }],
  [24, { name: "Leafless", replacements: remove("oak_leaves", "spruce_leaves", "birch_leaves", "jungle_leaves", "acacia_leaves", "dark_oak_leaves", "mangrove_leaves", "cherry_leaves", "azalea_leaves", "flowering_azalea_leaves") }],
  [25, { name: "Coarse earth", replacements: swap("dirt", "coarse_dirt") }],
  [26, { name: "Mycelium lawn", replacements: swap("grass_block", "mycelium") }],
  [27, { name: "Birch oak", replacements: swap("oak_planks", "birch_planks") }],
  [28, { name: "Red wool", replacements: swap("white_wool", "red_wool") }],
  [29, { name: "Cracked masonry", replacements: swap("stone_bricks", "cracked_stone_bricks") }],
  [30, { name: "Dense ice", replacements: swap("ice", "packed_ice") }],
  [31, { name: "No snow", replacements: remove("snow", "snow_layer", "powder_snow") }],
  [32, { name: "Cobble fences", replacements: swap("oak_fence", "cobblestone_wall") }],
  [33, { name: "Iron doors", replacements: swap("oak_door", "iron_door") }],
  [34, { name: "Living ladders", replacements: swap("ladder", "vine") }],
  [35, { name: "Hay library", replacements: swap("bookshelf", "hay_block") }],
  [36, { name: "Barrel chests", replacements: swap("chest", "barrel") }],
  [37, { name: "No cobwebs", replacements: remove("web") }],
  [38, { name: "Nether bricks", replacements: swap("bricks", "nether_bricks") }],
  [39, { name: "Fired clay", replacements: swap("clay", "terracotta") }],
  [40, { name: "Charred terracotta", replacements: swap("terracotta", "black_terracotta") }],
  [41, { name: "Gray concrete", replacements: swap("white_concrete", "gray_concrete") }],
  [42, { name: "False redstone", replacements: swap("redstone_ore", "gold_ore") }],
  [43, { name: "Deep coal", replacements: swap("coal_ore", "deepslate_coal_ore") }],
  [44, { name: "Copper iron", replacements: swap("iron_ore", "copper_ore") }],
  [45, { name: "Gilded gold", replacements: swap("gold_ore", "diamond_ore") }],
  [46, { name: "Sandy gravel", replacements: swap("gravel", "sand") }],
  [47, { name: "Frozen water", replacements: swap("water", "ice") }],
  [48, { name: "Cold lava", replacements: swap("lava", "obsidian") }],
  [49, { name: "Soul nether", replacements: swap("netherrack", "soul_sand") }],
  [50, { name: "Magma souls", replacements: swap("soul_sand", "magma") }],
  [51, { name: "Purpur end", replacements: swap("end_stone", "purpur_block") }],
  [52, { name: "Crying obsidian", replacements: swap("obsidian", "crying_obsidian") }],
  [53, { name: "Melon pumpkins", replacements: swap("pumpkin", "melon_block") }],
  [54, { name: "Furnace tables", replacements: swap("crafting_table", "furnace") }],
  [55, { name: "Blast furnaces", replacements: swap("furnace", "blast_furnace") }],
  [56, { name: "No cauldrons", replacements: remove("cauldron") }],
  [57, { name: "Powered rails", replacements: swap("rail", "golden_rail") }],
  [58, { name: "Broken circuits", replacements: remove("redstone_wire") }],
  [59, { name: "Missing levers", replacements: remove("lever") }],
  [60, { name: "Stone pressure", replacements: swap("oak_pressure_plate", "stone_pressure_plate") }],
  [61, { name: "Unwritten", replacements: remove("standing_sign", "wall_sign", "oak_hanging_sign") }],
  [62, { name: "No banners", replacements: remove("standing_banner", "wall_banner") }],
  [63, { name: "Bedless", replacements: remove("bed") }],
  [64, { name: "No candles", replacements: remove("candle", "white_candle", "orange_candle", "magenta_candle", "light_blue_candle", "yellow_candle", "lime_candle", "pink_candle", "gray_candle", "light_gray_candle", "cyan_candle", "purple_candle", "blue_candle", "brown_candle", "green_candle", "red_candle", "black_candle") }],
  [65, { name: "Soul fires", replacements: swap("campfire", "soul_campfire") }],
  [66, { name: "Soul lanterns", replacements: swap("lantern", "soul_lantern") }],
  [67, { name: "Fungal glow", replacements: swap("glowstone", "shroomlight") }],
  [68, { name: "Prismarine lamps", replacements: swap("sea_lantern", "prismarine") }],
  [69, { name: "Mossy cobble", replacements: swap("cobblestone", "mossy_cobblestone") }],
  [70, { name: "No vines", replacements: remove("vine", "cave_vines", "cave_vines_body_with_berries", "cave_vines_head_with_berries") }],
  [71, { name: "Bamboo cactus", replacements: swap("cactus", "bamboo") }],
  [72, { name: "No sugar cane", replacements: remove("reeds") }],
  [73, { name: "Empty ponds", replacements: remove("waterlily") }],
  [74, { name: "Muddy farms", replacements: swap("farmland", "mud") }],
  [75, { name: "Podzol paths", replacements: swap("grass_path", "podzol") }],
  [76, { name: "Clay mud", replacements: swap("mud", "clay") }],
  [77, { name: "Calcite dripstone", replacements: swap("dripstone_block", "calcite") }],
  [78, { name: "Basalt tuff", replacements: swap("tuff", "basalt") }],
  [79, { name: "Diorite granite", replacements: swap("granite", "diorite") }],
  [80, { name: "Andesite diorite", replacements: swap("diorite", "andesite") }],
  [81, { name: "Granite andesite", replacements: swap("andesite", "granite") }],
  [82, { name: "Red sandstone", replacements: swap("sandstone", "red_sandstone") }],
  [83, { name: "Bone quartz", replacements: swap("quartz_block", "bone_block") }],
  [84, { name: "Copper iron", replacements: swap("iron_block", "copper_block") }],
  [85, { name: "Emerald gold", replacements: swap("gold_block", "emerald_block") }],
  [86, { name: "Lapis diamond", replacements: swap("diamond_block", "lapis_block") }],
  [87, { name: "Redstone emerald", replacements: swap("emerald_block", "redstone_block") }],
  [88, { name: "Hay targets", replacements: swap("target", "hay_block") }],
  [89, { name: "Slime honey", replacements: swap("honey_block", "slime") }],
  [90, { name: "Honey slime", replacements: swap("slime", "honey_block") }],
  [91, { name: "Soaked sponge", replacements: swap("sponge", "wet_sponge") }],
  [92, { name: "Dead coral", replacements: [["tube_coral_block", "dead_tube_coral_block"], ["brain_coral_block", "dead_brain_coral_block"], ["bubble_coral_block", "dead_bubble_coral_block"], ["fire_coral_block", "dead_fire_coral_block"], ["horn_coral_block", "dead_horn_coral_block"]] }],
  [93, { name: "Red glass", replacements: swap("glass", "red_stained_glass") }],
  [94, { name: "No trapdoors", replacements: remove("trapdoor", "spruce_trapdoor", "birch_trapdoor", "jungle_trapdoor", "acacia_trapdoor", "dark_oak_trapdoor", "mangrove_trapdoor", "cherry_trapdoor", "bamboo_trapdoor", "iron_trapdoor") }],
  [95, { name: "Fences become walls", replacements: [["oak_fence", "stone_brick_wall"], ["spruce_fence", "stone_brick_wall"], ["birch_fence", "stone_brick_wall"], ["jungle_fence", "stone_brick_wall"], ["acacia_fence", "stone_brick_wall"], ["dark_oak_fence", "stone_brick_wall"]] }],
  [96, { name: "End rod chains", replacements: swap("chain", "end_rod") }],
  [97, { name: "No scaffolding", replacements: remove("scaffolding") }],
  [98, { name: "Abandoned apiaries", replacements: remove("beehive", "bee_nest") }],
  [99, { name: "No storage", replacements: remove("chest", "trapped_chest", "barrel", "ender_chest") }],
  [100, { name: "Blackstone everything", scan: { type: "solidify", block: "blackstone" } }]
]);

export function getRealityRecipe(reality) {
  return REALITY_RECIPES.get(reality) ?? { name: `Reality ${reality}` };
}
